version: 2.1

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - run: echo 'CI done'

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
